import os

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

SYMBOL = "GC=F"
TIMEFRAME = "1m"

SCAN_INTERVAL = 300
LOOKBACK_CANDLES = 45

MIN_GAP = 5
MAX_GAP = 7

ALERT_PERCENT = 90
